substitutions:
  device_name: "powmr-inverter"
  node_name: "PowMr Inverter"
  node_id: powmr_inverter
  inverter_tx_pin: GPIO16
  inverter_rx_pin: GPIO17
  inverter_voltage_offset: "0"
  pzem_tx_pin: GPIO22
  pzem_rx_pin: GPIO23
  pzem1_voltage_offset: "0"
  pzem1_current_offset: "0.00"
  pzem2_voltage_offset: "0"
  pzem2_current_offset: "0.00"
  update_interval: 30s # Minimum 10s recommended to avoid duplicate command errors
  select_skip_updates: "2"
  pzem1_update_interval: 6s # Needs to be 1/5 of update interval because of smoothing filter on pzem readings
  pzem2_update_interval: 15s

esp32:
  board: esp32dev
  framework:
    type: esp-idf

packages:
  main: !include powmr-inverter/main.yaml
  # You can replace next 2 lines with your common configs for all devices
  common_system: !include includes/common_system.yaml
  common_sensors: !include includes/common_sensors.yaml

# Enable logging
logger:
#  level: WARN
  level: VERBOSE
#  level: VERY_VERBOSE
#  level: DEBUG
  logs:
    component: ERROR # Fix for issue #4717 "Component xxxxxx took a long time for an operation"
#    modbus_controller: VERBOSE
#    modbus_controller.text_sensor: WARN
#    modbus_controller.sensor: WARN
#    modbus_controller.binary_sensor: WARN
#    modbus_controller.select: WARN
time:
  - platform: homeassistant
    id: hass_time

#web_server:
#  port: 80
#  ota: false
